#company
company:
    type: rest
    resource: AppBundle\Rest\Company\CompanyController
    name_prefix: api_

customer:
    type: rest
    resource: AppBundle\Rest\Customer\CustomerController
    name_prefix: api_

home:
    type: rest
    resource: AppBundle\Rest\HomeController
    name_prefix: api_
#
#delegate:
#    type: rest
#    resource: AppBundle\Rest\Company\DelegateController
#    name_prefix: api_