app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults: {_locale: 'en'}

rest:
    type: rest
    resource: "routing_rest.yml"
    prefix : /{_locale}/api

