    # To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\Customer:
            algorithm: md5
            iterations: 0
            encode_as_base64: false

        AppBundle\Security\User\CustomerUser:
            algorithm: md5
            iterations: 0
            encode_as_base64: false

        AppBundle\Security\User\CompanyUser:
            algorithm: md5
            iterations: 0
            encode_as_base64: false

        AppBundle\Security\User\AdminUser:
            algorithm: md5
            iterations: 0
            encode_as_base64: false

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

        customers:
            id: app.customer_user_provider

        companies:
            id: app.company_user_provider

        admins:
            id: app.admin_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:   ^/(%app_locales%)/api
            stateless: true
            wsse:      { lifetime: 180 }

        customer_area:
            context: my_context
            anonymous: ~
            pattern: ^/(%app_locales%)/customer/*
            form_login:
                login_path: customer_login
                check_path: customer_login
                default_target_path: customer_home
                provider: customers
            logout:
                path: customer_logout
                target: customer_login

        company_area:
            context: my_context
            anonymous: ~
            pattern: ^/(%app_locales%)/company/*
            form_login:
                login_path: company_login
                check_path: company_login
                default_target_path: company_home
                provider: companies
            logout:
                path: company_logout
                target: company_login
        admin_area:
            context: my_context
            anonymous: ~
            pattern: ^/(%app_locales%)/admin/*
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: admin_home
                provider: admins
            logout:
                path: admin_logout
                target: admin_login

    access_control:
        - { path: ^/(%app_locales%)/customer/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%app_locales%)/customer, roles: ROLE_CUSTOMER }
        - { path: ^/(%app_locales%)/company/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%app_locales%)/company, roles: ROLE_COMPANY }
        - { path: ^/(%app_locales%)/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%app_locales%)/admin, roles: ROLE_ADMIN }
        - { path: ^/(%app_locales%)/api/, roles: ROLE_API  }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/vendor, roles: ROLE_VENDOR }
