# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']
    app.loyality:
        class: AppBundle\Services\Loyality
        arguments: ['@doctrine.orm.entity_manager','@translator']
    app.customer_user_provider:
        class: AppBundle\Security\User\CustomerUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    app.customer_authenticator:
        class: AppBundle\Security\CustomerAuthenticator
        arguments: ["@security.password_encoder"]
    app.company_user_provider:
        class: AppBundle\Security\User\CompanyUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    app.company_authenticator:
        class: AppBundle\Security\CompanyAuthenticator
        arguments: ["@security.password_encoder"]
    app.admin_user_provider:
        class: AppBundle\Security\User\AdminUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    app.admin_authenticator:
        class: AppBundle\Security\AdminAuthenticator
        arguments: ["@security.password_encoder"]

    appBundle.eventListeners.localeRewriteListener:
        class: AppBundle\EventListener\LocaleRewriteListener
        arguments: ["@router", "%kernel.default_locale%", "%locale_supported%"]
        tags:
          - { name: kernel.event_subscriber }


    wsse.security.authentication.provider:
        class: AppBundle\Security\Authentication\Provider\WsseProvider
        arguments: ['@doctrine.orm.entity_manager', '@cache.app', '']
        public: false

    wsse.security.authentication.listener:
        class: AppBundle\Security\Firewall\WsseListener
        arguments: ['@security.token_storage', '@security.authentication.manager']
        public: false