<?php
namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints as Assert;

class CustRegForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('email', EmailType::class)
            ->add('loyality_id', TextType::class)
            ->add('city', TextType::class)
            ->add('nationality', TextType::class)
            ->add('name', TextType::class)
            ->add('refferer_email', EmailType::class,
                array(
                    'mapped'=>false,
                    'constraints' =>
                        array(
                            new Email(),
                        )
                ))
            ->add('password', RepeatedType::class, array(
                'type' => PasswordType::class,
                'first_options' => array('label' => 'Password'),
                'second_options' => array('label' => 'Confirm Password'),
                    
                )
            )
//            ->add('is_active', ChoiceType::class, array(
//                'choices'  => array(
//                    'Enabled' => '1',
//                    'Disabled' => '0',
//                ),
//            )
//            )
//            ->add('submit', SubmitType::class, array('label'=>'Save', 'attr'=>array('class'=>'btn btn-custom btn-lg btn-block'))
//            )
        ;
    }

    public function configureOption(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Customer',
        ));
    }
}
?>