<?php

namespace AppBundle\Entity;

/**
 * ProdCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdCatRepository extends \Doctrine\ORM\EntityRepository
{
}
