<?php

namespace AppBundle\Entity;

/**
 * UsertypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsertypeRepository extends \Doctrine\ORM\EntityRepository
{
}
