<?php

namespace AppBundle\Entity\Repositories;
use AppBundle\Entity\CompanyDelegate;
use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyDelegateRepository extends EntityRepository
{

    /**
     * @param $email
     * @return string
     *
     * @return CompanyDelegate|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByEmail($email)
    {
        return $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:CompanyDelegate', 'c')
            ->where('c.email = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->getOneOrNullResult();
    }

    
}
