<?php

namespace AppBundle\Entity\Repositories;

/**
 * CustomerRefferalPointHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRefferalPointHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
