<?php

namespace AppBundle\Entity\Repositories;

/**
 * CustomerInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerInvitationRepository extends \Doctrine\ORM\EntityRepository
{
}
