<?php

namespace AppBundle\Entity\Repositories;

/**
 * CustomerRefferalHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRefferalHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
