<?php

namespace AppBundle\Entity\Repositories;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountRepository extends \Doctrine\ORM\EntityRepository
{

    public function getDiscountsByCompanyId($company){
        return $this->_em->createQueryBuilder()
            ->select('d')
            ->from('AppBundle:Discount', 'd')
            ->where("d.company  = :company")
            ->setParameter('company', $company)
            ->getQuery()
            ->getResult();
    }
}
