<?php

namespace AppBundle\Entity\Repositories;

/**
 * RefferalTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefferalTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
